<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">

		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<a class="navbar-brand" href="/">
				<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
				Back to Calendar
			</a>

		</div>

		<div class="collapse navbar-collapse" id="bs-collapse">
			<ul class="nav navbar-nav">
				<li><a href="/my_shows.php">My Shows</a></li>
			</ul>
			<form class="navbar-form navbar-right" role="search" action="/search.php">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search" name="search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>

	</div>
</nav>